"""empty message

Revision ID: 316a22151bda
Revises: c6bf38eb8187
Create Date: 2022-07-29 18:56:36.557552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316a22151bda'
down_revision = 'c6bf38eb8187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'seeking_desc')
    op.drop_column('Artist', 'looking_for_Venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking_for_Venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('seeking_desc', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###
